plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace "com.example.itravel"
    compileSdkVersion 36
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "com.example.itravel"
        minSdkVersion 26
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.13.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'androidx.fragment:fragment:1.8.5'
    implementation 'com.getbase:floatingactionbutton:1.10.1'

// FireBase
    implementation 'com.google.firebase:firebase-storage:20.3.0'
    implementation 'com.google.firebase:firebase-auth:22.3.1'
    implementation 'com.google.firebase:firebase-database:20.3.1'
    implementation 'com.google.firebase:firebase-firestore:24.10.3'

    implementation 'com.loopj.android:android-async-http:1.4.11'

    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

// Phone Flag and Country Code
    implementation 'com.hbb20:ccp:2.7.0'

// GIF Images in JSON Form
    implementation 'com.airbnb.android:lottie:6.3.0'

// Google Map
    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    implementation 'com.google.android.gms:play-services-location:21.3.0'
    implementation 'com.karumi:dexter:6.2.2'

// OSRM routing (Retrofit)
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'

// Circle Image View
    implementation 'com.mikhaellopez:circularimageview:4.3.1'

// Crop Image
    implementation 'com.vanniktech:android-image-cropper:4.5.0'
    implementation 'androidx.activity:activity-ktx:1.8.2'

// Glide
    implementation 'com.github.bumptech.glide:glide:4.16.0'
}